### ISSUE TITLE
-m parameter fails

### ISSUE THREAD

**Issue by martinreynaert** [proycon/spacy2folia#3]
Hi,

After testing I come to the conclusion that the -m or --model parameter utterly fails.

I have in the past overcome this bug by changing the hard-coded LM in the script. E.g. by changing:

``nlp = spacy.load("en_core_web_sm")`` 

into:

``nlp = spacy.load("de_core_news_sm")``

I hope you will be able to offer a more elegant solution by making the parameter work as advertised.

Thank you!

**Comment by proycon** [comment]
I can't replicate the problem. The ``--model`` / ``-m`` parameter seems to work fine. Can you give data and a full minimal example that shows it fails?
