### ISSUE TITLE
Tool's name 'spacy2folia' misnomer: suggestion for correction

### ISSUE THREAD

**Issue by martinreynaert** [proycon/spacy2folia#5]
Hi,

This is primarily a suggestion.

Since the tool has been expanded to also process already existing FoLiA, its name feels like a misnomer.

I would suggest changing it to 'spacy4folia', unless that is too inconvenient.

Thank you!

**Comment by proycon** [comment]
It's a bit of a misnomer nowadays yeah, originally the tool only did FoLiA output. Renaming is rather inconvenient indeed so I'll keep things are they are.
